version: '3'
services:
  jupyter-notebook:
    image: jupyter/pyspark-notebook
    container_name: jupyter
    volumes:
      - ./notebook:/home/jovyan/jupyter
    ports:
      - "8080:8888"
    shm_size: "5gb"

  psql-db:
    build: .
    container_name: psql-db
    ports:
      - "8082:5432"
    volumes:
      - ./db:/home/data
